version: "3.7"

networks:
  net:
    name: fabric_network
services:
  offchain_sat:
    image: postgres:13.0-alpine
    container_name: offchain_sat
    restart: always
    ports:
      - 6432:5432    
    environment:
      - DATABASE_DATABASE=offchaindata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres    
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - net       
 ishare_mw:
    image: isharefoundation/ishare-satellite-app-mw:v2.7
    ports:
      - 5001:21001
    volumes:
      - ./app-mw-config.yaml:/test/config/app-mw-config.yaml
      - ../jwt-rsa/jwtRSA256-private.pem:/jwtRSA256-private.pem
      - ../jwt-rsa/jwtRSA256-public.pem:/jwtRSA256-public.pem      
    restart: always      
    environment:
      - CONFIG_FILE_PATH=/test/config/app-mw-config.yaml
#      - GODEBUG=x509ignoreCN=0
    networks:
      - net 


 ishare_hlf:
    image: isharefoundation/ishare-satellite-hlf-mw:v1.7
    ports:
      - 4001:21001
    volumes:
      -  <path-to-crypto>:/var/hyperledger/crypto
      - ./hlf-mw-config.yaml:/config/hlf-mw-config.yaml
      - ./genesis.block:/tmp/channel/genesis.block
      - ./isharechannel.tx:/tmp/channel/channel.tx
    environment:
      - CONFIG_FILE_PATH=/config/hlf-mw-config.yaml
      - GODEBUG=x509ignoreCN=0
    restart: always      
    networks:
      - net       
